# Generated by Django 6.1 on 2026-09-11 00:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taller', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='estado',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 9, 10, 21, 13, 35, 400454)),
        ),
        migrations.AddField(
            model_name='estado',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='inventario',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 9, 10, 21, 13, 35, 400454)),
        ),
        migrations.AddField(
            model_name='inventario',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='ubicacion',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 9, 10, 21, 13, 35, 400454)),
        ),
        migrations.AddField(
            model_name='ubicacion',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
