# Generated by Django 6.1 on 2026-09-17 00:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taller', '0003_comuna_genero_idioma_pais_provincia_region_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ubicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=15)),
                ('ubicacion', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=255, null=True)),
                ('habilitado', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Copia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('habilitado', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taller.estado')),
                ('libro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taller.libro')),
                ('ubicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taller.ubicacion')),
            ],
        ),
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_prestamo', models.DateTimeField(auto_now_add=True)),
                ('fecha_devolucion', models.DateTimeField()),
                ('fecha_retorno', models.DateTimeField(null=True)),
                ('lector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taller.usuario')),
                ('libro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taller.copia')),
            ],
        ),
    ]
