# Generated by Django 6.1 on 2026-09-24 22:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taller', '0004_ubicacion_copia_prestamo'),
    ]

    operations = [
        migrations.AlterModelTableComment(
            name='autor',
            table_comment='Datos de autores asociados a publicaciones/libros.',
        ),
        migrations.AlterModelTableComment(
            name='biblioteca',
            table_comment='Datos de biblioteca.',
        ),
        migrations.AlterModelTableComment(
            name='comuna',
            table_comment='Comunas de Chile, data de SUBDERE. Pertenece a una provincia específica.',
        ),
        migrations.AlterModelTableComment(
            name='direccion',
            table_comment='Provincias de Chile, data de SUBDERE. Pertenece a una región específica.',
        ),
        migrations.AlterModelTableComment(
            name='edicion',
            table_comment='Data específica de una publicación realizada por una editorial.',
        ),
        migrations.AlterModelTableComment(
            name='editorial',
            table_comment='Datos de empresas encargadas de publicaciones.',
        ),
        migrations.AlterModelTableComment(
            name='estado',
            table_comment='Data de estado físico de ejemplares en la biblioteca.',
        ),
        migrations.AlterModelTableComment(
            name='genero',
            table_comment='Géneros literarios asociados a subgéneros.',
        ),
        migrations.AlterModelTableComment(
            name='idioma',
            table_comment='Data de idiomas para asociar a publicaciones.',
        ),
        migrations.AlterModelTableComment(
            name='libro',
            table_comment='Data específica de libros publicados pertenecientes a la bilbioteca.',
        ),
        migrations.AlterModelTableComment(
            name='pais',
            table_comment='Información de paises del mundo, para asociar a autores y lectores.',
        ),
        migrations.AlterModelTableComment(
            name='prestamo',
            table_comment='Registro de préstamo de libros en la biblioteca.',
        ),
        migrations.AlterModelTableComment(
            name='provincia',
            table_comment='Provincias de Chile, data de SUBDERE. Pertenece a una región específica.',
        ),
        migrations.AlterModelTableComment(
            name='region',
            table_comment='Regiones de Chile, data de SUBDERE.',
        ),
        migrations.AlterModelTableComment(
            name='subgenero',
            table_comment='Subgéneros literarios asociados a publicaciones/libros.',
        ),
        migrations.AlterModelTableComment(
            name='ubicacion',
            table_comment='Data de ubicación física de ejemplares en la biblioteca.',
        ),
        migrations.AlterModelTableComment(
            name='usuario',
            table_comment='Registro de usuarios de biblioteca.',
        ),
        migrations.AlterField(
            model_name='autor',
            name='biografia',
            field=models.TextField(null=True, verbose_name='Biografía'),
        ),
        migrations.AlterField(
            model_name='autor',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha Creación'),
        ),
        migrations.AlterField(
            model_name='autor',
            name='fecha_defuncion',
            field=models.DateField(null=True, verbose_name='Fecha Defunción'),
        ),
        migrations.AlterField(
            model_name='autor',
            name='fecha_nacimiento',
            field=models.DateField(null=True, verbose_name='Fecha Nacimiento'),
        ),
        migrations.AlterField(
            model_name='autor',
            name='habilitado',
            field=models.BooleanField(default=True, verbose_name='Habilitado'),
        ),
        migrations.AlterField(
            model_name='autor',
            name='nombre',
            field=models.CharField(max_length=100, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='autor',
            name='pseudonimo',
            field=models.CharField(max_length=50, null=True, verbose_name='Pseudónimo'),
        ),
        migrations.AlterField(
            model_name='autor',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha Actualización'),
        ),
        migrations.AlterField(
            model_name='biblioteca',
            name='correo',
            field=models.EmailField(max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='biblioteca',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha Creación'),
        ),
        migrations.AlterField(
            model_name='biblioteca',
            name='habilitado',
            field=models.BooleanField(default=True, verbose_name='Habilitado'),
        ),
        migrations.AlterField(
            model_name='biblioteca',
            name='nombre',
            field=models.CharField(max_length=50, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='biblioteca',
            name='telefono',
            field=models.CharField(max_length=15, null=True, verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='biblioteca',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha Actualización'),
        ),
        migrations.AlterField(
            model_name='biblioteca',
            name='web',
            field=models.URLField(null=True, verbose_name='WWW'),
        ),
        migrations.AlterField(
            model_name='comuna',
            name='codigo',
            field=models.CharField(max_length=5, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='comuna',
            name='comuna',
            field=models.CharField(max_length=60, verbose_name='Comuna'),
        ),
        migrations.AlterField(
            model_name='comuna',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha Creación'),
        ),
        migrations.AlterField(
            model_name='comuna',
            name='habilitado',
            field=models.BooleanField(default=True, verbose_name='Habilitado'),
        ),
        migrations.AlterField(
            model_name='comuna',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha Actualización'),
        ),
        migrations.AlterField(
            model_name='direccion',
            name='calle',
            field=models.CharField(max_length=100, null=True, verbose_name='Calle'),
        ),
        migrations.AlterField(
            model_name='direccion',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha Creación'),
        ),
        migrations.AlterField(
            model_name='direccion',
            name='departamento',
            field=models.CharField(max_length=10, null=True, verbose_name='Dpto/Oficina'),
        ),
        migrations.AlterField(
            model_name='direccion',
            name='habilitado',
            field=models.BooleanField(default=True, verbose_name='Habilitado'),
        ),
        migrations.AlterField(
            model_name='direccion',
            name='numero',
            field=models.CharField(max_length=10, null=True, verbose_name='Número'),
        ),
        migrations.AlterField(
            model_name='direccion',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha Actualización'),
        ),
        migrations.AlterField(
            model_name='edicion',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha Creación'),
        ),
        migrations.AlterField(
            model_name='edicion',
            name='fecha_edicion',
            field=models.DateField(verbose_name='Fecha Edición'),
        ),
        migrations.AlterField(
            model_name='edicion',
            name='habilitado',
            field=models.BooleanField(default=True, verbose_name='Habilitado'),
        ),
        migrations.AlterField(
            model_name='edicion',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha Actualización'),
        ),
        migrations.AlterField(
            model_name='editorial',
            name='correo',
            field=models.EmailField(max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='editorial',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha Creación'),
        ),
        migrations.AlterField(
            model_name='editorial',
            name='habilitado',
            field=models.BooleanField(default=True, verbose_name='Habilitado'),
        ),
        migrations.AlterField(
            model_name='editorial',
            name='nombre',
            field=models.CharField(max_length=50, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='editorial',
            name='telefono',
            field=models.CharField(max_length=15, null=True, verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='editorial',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha Actualización'),
        ),
        migrations.AlterField(
            model_name='editorial',
            name='web',
            field=models.URLField(null=True, verbose_name='WWW'),
        ),
        migrations.AlterField(
            model_name='estado',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha Creación'),
        ),
        migrations.AlterField(
            model_name='estado',
            name='descripcion',
            field=models.CharField(max_length=255, null=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='estado',
            name='estado',
            field=models.CharField(max_length=30, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='estado',
            name='habilitado',
            field=models.BooleanField(default=True, verbose_name='Habilitado'),
        ),
        migrations.AlterField(
            model_name='estado',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha Actualización'),
        ),
        migrations.AlterField(
            model_name='genero',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha Creación'),
        ),
        migrations.AlterField(
            model_name='genero',
            name='descripcion',
            field=models.CharField(max_length=255, null=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='genero',
            name='genero',
            field=models.CharField(max_length=30, verbose_name='Género Literario'),
        ),
        migrations.AlterField(
            model_name='genero',
            name='habilitado',
            field=models.BooleanField(default=True, verbose_name='Habilitado'),
        ),
        migrations.AlterField(
            model_name='genero',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha Actualización'),
        ),
        migrations.AlterField(
            model_name='idioma',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha Creación'),
        ),
        migrations.AlterField(
            model_name='idioma',
            name='habilitado',
            field=models.BooleanField(default=True, verbose_name='Habilitado'),
        ),
        migrations.AlterField(
            model_name='idioma',
            name='idioma',
            field=models.CharField(max_length=30, verbose_name='Idioma'),
        ),
        migrations.AlterField(
            model_name='idioma',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha Actualización'),
        ),
        migrations.AlterField(
            model_name='libro',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha Creación'),
        ),
        migrations.AlterField(
            model_name='libro',
            name='habilitado',
            field=models.BooleanField(default=True, verbose_name='Habilitado'),
        ),
        migrations.AlterField(
            model_name='libro',
            name='paginas',
            field=models.IntegerField(verbose_name='Cantidad Páginas'),
        ),
        migrations.AlterField(
            model_name='libro',
            name='titulo',
            field=models.CharField(max_length=150, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='libro',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha Actualización'),
        ),
        migrations.AlterField(
            model_name='pais',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha Creación'),
        ),
        migrations.AlterField(
            model_name='pais',
            name='habilitado',
            field=models.BooleanField(default=True, verbose_name='Habilitado'),
        ),
        migrations.AlterField(
            model_name='pais',
            name='iso_2',
            field=models.CharField(max_length=2, verbose_name='ISO 2'),
        ),
        migrations.AlterField(
            model_name='pais',
            name='iso_3',
            field=models.CharField(max_length=3, verbose_name='ISO 3'),
        ),
        migrations.AlterField(
            model_name='pais',
            name='nacionalidad',
            field=models.CharField(max_length=30, verbose_name='Nacionalidad'),
        ),
        migrations.AlterField(
            model_name='pais',
            name='nombre',
            field=models.CharField(max_length=50, verbose_name='País'),
        ),
        migrations.AlterField(
            model_name='pais',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha Actualización'),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='fecha_devolucion',
            field=models.DateTimeField(verbose_name='Fecha Devolución'),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='fecha_prestamo',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha Préstamo'),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='fecha_retorno',
            field=models.DateTimeField(null=True, verbose_name='Fecha Retorno'),
        ),
        migrations.AlterField(
            model_name='provincia',
            name='codigo',
            field=models.CharField(max_length=3, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='provincia',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha Creación'),
        ),
        migrations.AlterField(
            model_name='provincia',
            name='habilitado',
            field=models.BooleanField(default=True, verbose_name='Habilitado'),
        ),
        migrations.AlterField(
            model_name='provincia',
            name='provincia',
            field=models.CharField(max_length=50, verbose_name='Provincia'),
        ),
        migrations.AlterField(
            model_name='provincia',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha Actualización'),
        ),
        migrations.AlterField(
            model_name='region',
            name='codigo',
            field=models.CharField(max_length=2, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='region',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha Creación'),
        ),
        migrations.AlterField(
            model_name='region',
            name='habilitado',
            field=models.BooleanField(default=True, verbose_name='Habilitado'),
        ),
        migrations.AlterField(
            model_name='region',
            name='region',
            field=models.CharField(max_length=30, verbose_name='Región'),
        ),
        migrations.AlterField(
            model_name='region',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha Actualización'),
        ),
        migrations.AlterField(
            model_name='subgenero',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha Creación'),
        ),
        migrations.AlterField(
            model_name='subgenero',
            name='descripcion',
            field=models.CharField(max_length=255, null=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='subgenero',
            name='habilitado',
            field=models.BooleanField(default=True, verbose_name='Habilitado'),
        ),
        migrations.AlterField(
            model_name='subgenero',
            name='subgenero',
            field=models.CharField(max_length=30, verbose_name='Sub-Género Literario'),
        ),
        migrations.AlterField(
            model_name='subgenero',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha Actualización'),
        ),
        migrations.AlterField(
            model_name='ubicacion',
            name='codigo',
            field=models.CharField(max_length=15, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='ubicacion',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha Creación'),
        ),
        migrations.AlterField(
            model_name='ubicacion',
            name='descripcion',
            field=models.CharField(max_length=255, null=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='ubicacion',
            name='habilitado',
            field=models.BooleanField(default=True, verbose_name='Habilitado'),
        ),
        migrations.AlterField(
            model_name='ubicacion',
            name='ubicacion',
            field=models.CharField(max_length=50, verbose_name='Ubicación'),
        ),
        migrations.AlterField(
            model_name='ubicacion',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha Actualización'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='correo',
            field=models.EmailField(max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha Creación'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='fecha_nacimiento',
            field=models.DateField(verbose_name='Fecha Nacimiento'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='habilitado',
            field=models.BooleanField(default=True, verbose_name='Habilitado'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='nombre',
            field=models.CharField(max_length=150, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rut',
            field=models.CharField(max_length=12, verbose_name='RUT'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='telefono',
            field=models.CharField(max_length=15, null=True, verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha Actualización'),
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gtin', models.CharField(max_length=50, verbose_name='Código Barras')),
                ('habilitado', models.BooleanField(default=True, verbose_name='Habilitado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha Actualización')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taller.estado')),
                ('libro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taller.libro')),
                ('ubicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taller.ubicacion')),
            ],
            options={
                'db_table_comment': 'Copias de un libro disponibles para préstamos en biblioteca.',
            },
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='libro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taller.inventario'),
        ),
        migrations.DeleteModel(
            name='Copia',
        ),
    ]
