# Generated by Django 6.1 on 2026-10-01 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taller', '0005_alter_autor_table_comment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pais',
            name='nombre',
            field=models.CharField(max_length=60, verbose_name='País'),
        ),
    ]
